INSERT OR IGNORE INTO jobs (
  id, slug, status, title, company, company_url, city, state, postal_code, country,
  location_type, employment_type, pay_min, pay_max, pay_type, currency, description,
  apply_url, contact_email, owner_email, source_url, source_name, source_type, confidence,
  valid_through, expires_at, published_at, indexed_at, last_edited_at, created_at, updated_at
) VALUES
(
  'seed-biohazard-technician-indianapolis',
  'biohazard-remediation-technician-indianapolis-in-seed',
  'active',
  'Biohazard Remediation Technician',
  'Seed Listing',
  NULL,
  'Indianapolis',
  'IN',
  '46204',
  'US',
  'onsite',
  'FULL_TIME',
  24,
  32,
  'Hourly',
  'USD',
  'Local seed listing for development only. Replace with a verified employer listing before production launch.',
  'https://crimescenecleanerjobs.com/post',
  NULL,
  'owner@example.com',
  NULL,
  'Local Seed',
  'seed',
  1,
  datetime('now', '+45 days'),
  datetime('now', '+45 days'),
  datetime('now'),
  NULL,
  NULL,
  datetime('now'),
  datetime('now')
),
(
  'seed-trauma-scene-cleaner-columbus',
  'trauma-scene-cleaner-columbus-oh-seed',
  'pending',
  'Trauma Scene Cleaner',
  'Pending Seed Listing',
  NULL,
  'Columbus',
  'OH',
  '43215',
  'US',
  'onsite',
  'FULL_TIME',
  22,
  30,
  'Hourly',
  'USD',
  'Pending local seed listing for testing the admin publish workflow.',
  'https://crimescenecleanerjobs.com/post',
  NULL,
  'owner@example.com',
  NULL,
  'Local Seed',
  'seed',
  1,
  datetime('now', '+45 days'),
  datetime('now', '+45 days'),
  NULL,
  NULL,
  NULL,
  datetime('now'),
  datetime('now')
);
